import pg from "pg";

const pool = new pg.Pool({
    user: "postgres",
    host: "localhost",
    database: "hairdressing",
    password: "postgres",
    port: 5433,
});

function createTable(queryString) {
    pool.query(queryString, (err, res) => {
        if (err) {
            if (err.stack.includes("already exists")) {
                console.log("Table already exists!");
            } else {
                console.error("Error executing query", err.stack);
            }
        } else {
            console.log("Table created");
        }
    });
}

async function runQueries(queries) {
    for (let i = 0; i < queries.length; i++) {
        await createTable(queries[i]);
    }
    await pool.end();
}

const queries = [
    `CREATE TABLE hairdresser (
        id int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        fname varchar(50) NOT NULL,
        lname varchar(50) NOT NULL,
        title varchar(5)
    );`,
    `CREATE TABLE customer (
        email varchar(75) PRIMARY KEY,
        fname varchar(50) NOT NULL,
        lname varchar(50) NOT NULL,
        title varchar(5)
    );`,
    `CREATE TABLE treatment (
        id int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        name varchar(50),
        description varchar(150),
        price money,
        minutes int
    );`,
    `CREATE TABLE appointment (
        id int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        customer_email varchar(75) REFERENCES customer(email),
        hairdresser_id int REFERENCES hairdresser(id),
        date_time timestamp NOT NULL,
        type_id int REFERENCES treatment(id)
    );`,
];

runQueries(queries);
